apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photo-app
  template:
    metadata:
      labels:
        app: photo-app
    spec:
      containers:
      - name: photo-app
        image: 885657313466.dkr.ecr.ap-south-1.amazonaws.com/photo-app:upload
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: photo-app-db-secret
        - secretRef:
            name: photo-app-s3-secret


